export { default as Header } from './header.jsx'
export { default as Footer } from './footer.jsx'
export { default as Section1 } from './section1.jsx'
export { default as Section2 } from './section2.jsx'
export { default as Section3 } from './section3.jsx'
export { default as Section4 } from './section4.jsx'
