export { default as Author } from './author.jsx'
export { default as Error } from './error.jsx'
export { default as Newsletter } from './newsletter.jsx'
export { default as RelatedPosts } from './relatedposts.jsx'
export { default as Spinner } from './spinner.jsx'
